.gitignore
README.md

README.md - init

---

CONTRIBUTING.md
LICENSE.TXT
README.md
SECURITY.md

Signed-off-by: Kush Trivedi <kushthedude@gmail.com>

feat: add pre-requisities documentation for the orkestra project

---

README.md

Updated the verbiage and added opensource 3rd party project links.

Update README.md with project links

---

README.md

Refined the language and added some more clarity to the README.md
doc

Refine README.md language and add clarity

---

assets/uml/failure.puml
assets/uml/sequence.puml

Add PUML sequence diagrams

---

Makefile
azure-pipelines.yml
scripts/setup-kubebuilder.sh

Signed-off-by: Kush Trivedi <kushthedude@gmail.com>

feat: add make target for kubebuilder setup

---

chart/orkestra/templates/deployment.yaml
pkg/workflow/argo.go

Revert "nitishm/task/50/service-account-env"

---

chart/orkestra/templates/deployment.yaml
config/crd/bases/orkestra.azure.microsoft.com_applicationgroups.yaml
config/crd/bases/orkestra.azure.microsoft.com_applications.yaml
pkg/workflow/argo.go

Fixes #50
Create ENV variable for workflow's job pod serviceAccount

Make workflow pod serviceAccount configurable

---

Dockerfile
chart/orkestra/templates/configmap.yaml
chart/orkestra/templates/deployment.yaml
chart/orkestra/values.yaml
config.yaml

config.yaml parsed from mounted configmap volume
Fixes #56

Configmap for config.yaml

---

chart/orkestra/templates/configmap.yaml
pkg/workflow/argo.go

Fix missplaced curly brace in configmap.yaml tpl

---

README.md

Add roadmap section

---

controllers/appgroup_controller.go

file:// should be considered as an embedded chart

---

controllers/appgroup_reconciler.go

Initialize the status application sc map

---

controllers/appgroup_controller.go

Add and handle finalizer for DELETE handling

---

controllers/appgroup_controller.go

Fix failure during update

---

controllers/appgroup_controller.go

Set the spec values to the passed in overlay values' value

Finalizer update failure handling improvement

---

controllers/appgroup_controller.go
controllers/appgroup_reconciler.go
pkg/workflow/argo.go

Fixes #88
Fixed ns termination status by reconciling

Fixed ns termination status by reconciling

---

pkg/workflow/argo.go

Fix dependency template ref naming to DNS1123 comp

---

controllers/appgroup_reconciler.go

Handle charts for staging with no template files

---

examples/simple/dev-applicationgroup.yaml
pkg/workflow/argo.go

Fixes #98
Set HelmRelease's 'ReleaseName' to the CRO name

Set HelmRelease's 'ReleaseName' to the CRO name

---

controllers/appgroup_reconciler.go

If templates/ with only tpl files treat as empty

---

controllers/appgroup_reconciler.go

Minor fix for tpl yaml check

---

controllers/appgroup_controller.go

Fix incorrect annotation check to tag with last successful workflow

---

controllers/appgroup_controller.go
pkg/helm.go

Use helm package actions for rollback and uninstall

---

controllers/appgroup_controller.go

Reconcile successful workflow asap

---

pkg/workflow/argo.go

Increase HR timeout to 1h

---

controllers/appgroup_reconciler.go
pkg/helpers.go
pkg/workflow/argo.go

Limit length of names to be below 63 chars

---

TODOs.md

TODOs to support helm-controller

TODOs to support helm-controller

---

api/v1alpha1/appgroup_types.go
controllers/appgroup_controller.go
pkg/registry/pull.go
pkg/registry/push.go

Added comments to the reconciler and types

---

config/samples/bookinfo.yaml

Remove groupID from sample

---

docs/DEVELOPMENT.md

Tutorial for bridge to kubernetes

---

chart/orkestra/templates/deployment.yaml
chart/orkestra/values.yaml
controllers/appgroup_controller.go
pkg/registry/options.go

Create target dir if it doesnt exist

---

chart/orkestra/values.yaml
main.go
pkg/workflow/argo.go

[WIP] Configure pod parallelism to higher value

---

pkg/workflow/argo.go

Cleanup workflow pods on workflow success

---

controllers/appgroup_controller.go

Status of the applicationgroup should be dependent on the workflow rollout step reaching a current state, not the helmrelease status conditions
Closes #190

Status Just Checks Workflow Status

---

docs/api.md

Fix the api docs to be consistent with the latest changes to the CRD
Closes #195

Update the API Docs

---

main.go
pkg/probe.go

- Fix crashing by retrying to set-up the helm repository before starting the manager
Closes #202

Fix CrashLoopBackoff when starting Orkestra

---

examples/simple/bookinfo.yaml
pkg/workflow/argo.go

Use release.timeout as the timeout for the defaultExecutor

---

controllers/appgroup_reconciler.go
pkg/workflow/argo.go

Convert app chart name to dns1123 comp when staging

---

controllers/appgroup_reconciler.go

Ignore misc files from parent to subchart

---

chart/orkestra/templates/deployment.yaml
chart/orkestra/values.yaml

Update helm chart values after debug/log-level flags change

---

pkg/workflow/argo.go
pkg/workflow/consts.go

The action "Install" and "Delete" will be used for forward and reverse workflows respectively.
Should go with orkestra-workflow-executor [PR](https://github.com/Azure/orkestra-workflow-executor/pull/1).

Changes for using action parameter of orkestra workflow executor

---

chart/orkestra/values.yaml

Debug should be disabled by default

---

docs/developers.md

Update developer docs with makefile tutorial

---

README.md

Make the status badge link navigate to the right URLs and not just show the badge.

Fix status badge links in README.md

---

pkg/utils/helpers.go
pkg/utils/helpers_test.go

Fix bug where IsFileYaml() returns true if non yaml file's extension contains suffix yaml or yml

---

controllers/appgroup_controller.go

Just eyeballed this today. If someone were to bring their own finalizer, we would be broken since we would not add our finalizer

Fix Adding Finalizer Bug

---

api/v1alpha1/appgroup_types.go

bug fix: assignment to entry in nil map returned by GetValues()

---

chart/orkestra/values.yaml

Workflow serviceaccount not using orkestra SA

---

controllers/appgroup_controller.go

Fix finalizer check

---

pkg/workflow/errors.go
pkg/workflow/graph.go

Fix invalid pointer and slice bug in Graph.bft()

---

.github/workflows/e2e.yaml

Upgrade CI/CD to Newest Version of Kind

---

docs/developers.md

Add custom executor example to docs

---

examples/custom/generic-bookinfo.yaml

Custom executor example
